apiVersion: v2
name: kagent-crds
description: A Helm chart that references the official "kagent-crds" Helm chart.
type: application
version: 0.3.13
dependencies:
  - name: kagent-crds
    version: 0.3.13
    repository: oci://ghcr.io/kagent-dev/kagent/helm
