apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: kagent-crds-0-3-13
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: kagent-crds
      version: 0.3.13
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: k0rdent-catalog
