apiVersion: v2
name: ray-cluster
description: A Helm chart that references the official "ray-cluster" Helm chart.
type: application
version: 1.3.2
dependencies:
  - name: ray-cluster
    version: 1.3.2
    repository: https://ray-project.github.io/kuberay-helm/
