apiVersion: v2
name: kuberay-operator
description: A Helm chart that references the official "kuberay-operator" Helm chart.
type: application
version: 1.3.2
dependencies:
  - name: kuberay-operator
    version: 1.3.2
    repository: https://ray-project.github.io/kuberay-helm/
