title: "Grafana"
tags:
  - Monitoring
summary: "The open-source platform for monitoring and observability."
logo: "./assets/icon.svg" # https://commons.wikimedia.org/wiki/File:Grafana_icon.svg#file
created: "2025-08-27T13:06:51Z"
description: |
  Grafana allows you to query, visualize, alert on and understand your metrics no matter where they are stored. Create, explore, and share dashboards with your team and foster a data-driven culture:

  - **Visualizations:** Fast and flexible client side graphs with a multitude of options. Panel plugins offer many different ways to visualize metrics and logs.
  - **Dynamic Dashboards:** Create dynamic & reusable dashboards with template variables that appear as dropdowns at the top of the dashboard.
  - **Explore Metrics:** Explore your data through ad-hoc queries and dynamic drilldown. Split view and compare different time ranges, queries and data sources side by side.
  - **Explore Logs:** Experience the magic of switching from metrics to logs with preserved label filters. Quickly search through all your logs or streaming them live.
  - **Alerting:** Visually define alert rules for your most important metrics. Grafana will continuously evaluate and send notifications to systems like Slack, PagerDuty, VictorOps, OpsGenie.
  - **Mixed Data Sources:** Mix different data sources in the same graph! You can specify a data source on a per-query basis. This works for even custom datasources.
charts:
  - name: grafana
    versions: ['9.3.6']
deploy_code: |
  ~~~yaml
  apiVersion: k0rdent.mirantis.com/v1beta1
  kind: MultiClusterService
  metadata:
    name: grafana
  spec:
    clusterSelector:
      matchLabels:
        group: demo
    serviceSpec:
      services:
      - template: grafana-9-3-6
        name: grafana
        namespace: grafana
  ~~~
doc_link: https://grafana.com/docs/grafana/latest/setup-grafana/installation/helm/
